test

diff --git a/.circleci/images/primary/Dockerfile b/.circleci/images/primary/Dockerfile
--- a/.circleci/images/primary/Dockerfile
+++ b/.circleci/images/primary/Dockerfile
@@ -1,4 +1,5 @@
 FROM debian:buster-slim
+ARG DOCKER_CREDENTIAL_HELPER_VERSION=0.6.3
 
 #install and source
 RUN set -ex && apt-get update && apt-get upgrade && apt-get install -y \
@@ -37,13 +38,13 @@ RUN set -ex && \
     curl -fsSL https://download.docker.com/linux/debian/gpg | \
     gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
 
-## set up the stable repository
+## Set up the stable repository
 RUN set -ex && \
     echo \
     "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
     $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
 
-## install the latest version of Docker Engine and containerd
+## Install the latest version of Docker Engine and containerd
 RUN set -ex && apt-get update && apt-get upgrade && apt-get install -y \
     docker-ce \
     docker-ce-cli\
@@ -56,14 +57,28 @@ RUN set -ex && apt-get remove -y \
     lsb-release
 
 ## Verify docker installation
-RUN set -ex && \
-    docker --version
+RUN set -ex && docker --version
 
-# installing docker credential helper
+# Installing docker credential helper
+RUN set -ex && apt-get update && apt-get upgrade && apt-get install -y \
+    wget
 
+RUN set -ex && echo $PATH && \
+    cd /usr/local/bin && \
+    wget https://github.com/docker/docker-credential-helpers/releases/download/v${DOCKER_CREDENTIAL_HELPER_VERSION}/docker-credential-pass-v${DOCKER_CREDENTIAL_HELPER_VERSION}-amd64.tar.gz && \
+    tar -xvf docker-credential-pass-v${DOCKER_CREDENTIAL_HELPER_VERSION}-amd64.tar.gz && \
+    chmod +x docker-credential-pass && \
+    chown root:root /usr/local/bin/docker-credential-pass && \
+    rm docker-credential-pass-v${DOCKER_CREDENTIAL_HELPER_VERSION}-amd64.tar.gz
 
+## Clean up tools
+RUN set -ex && apt-get remove -y wget
 
+## Verify docker credential helper installation
+RUN set -ex && /usr/local/bin/docker-credential-pass version
 
+## Cleanup
+RUN apt-get -y --purge autoremove
 
 RUN echo "Finished building docker!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
 
